name: Version and Tag

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  version_and_tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
      - name: Install dependencies
        run: npm ci

      - name: Get current version
        id: get_version
        run: |
          VERSION=$(npm version --json | jq -r .version)
          echo "current_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Increment version
        id: increment_version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          NEW_VERSION=$(npm version patch --json)
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit package.json
        run: |
          git add .
          git commit -m "Bump version to ${{ steps.increment_version.outputs.new_version }}"

      - name: Create tag
        run: git tag ${{ steps.increment_version.outputs.new_version }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
